spring:
  application:
    name: PhotoGallery
  thymeleaf:
    cache: false
  servlet:
    context-path: /
logging:
  level:
    com:
      kevo:
        PhotoGallery:
          PhotoGalleryApplication: DEBUG
    org:
      springframework:
        web: DEBUG
aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_BUCKET_NAME}