spring:
  application:
    name: PhotoGallery
  config:
    import: file:.env[.properties]
  thymeleaf:
    cache: false
server:
  port: ${PORT}
  servlet:
    context-path: /
logging:
  level:
    com:
      kevo:
        PhotoGallery:
          PhotoGalleryApplication: DEBUG
    org:
      springframework:
        web: DEBUG